package co.in.mobilepay.application;

import android.content.Context;

import com.google.android.gms.analytics.GoogleAnalytics;
import com.google.android.gms.analytics.Tracker;

import java.util.HashMap;
import java.util.Map;

import co.in.mobilepay.R;

/**
 *
 * A collection of Google Analytics trackers. Fetch the tracker you need using
 * {@code AnalyticsTrackers.getInstance().get(...)}
 * <p/>
 * This code was generated by Android Studio but can be safely modified by
 * hand at this point.
 * <p/>
 * TODO: Call {@link #initialize(Context)} from an entry point in your app
 * before using this!
 *
 *  Created by Nithishkumar on 7/23/2016.
 *
 * Thanks to http://www.androidhive.info/2015/08/android-integrating-google-analytics-v4/
 */
public final class MobilePayAnalyticsConf {

    public enum Target {
        APP,
        // Add more trackers here if you need, and update the code in #get(Target) below
    }


    private static MobilePayAnalyticsConf sInstance;

    public static synchronized void initialize(Context context) {
        if (sInstance != null) {
            throw new IllegalStateException("Extra call to initialize analytics trackers");
        }

        sInstance = new MobilePayAnalyticsConf(context);
    }

    public static synchronized MobilePayAnalyticsConf getInstance() {
        if (sInstance == null) {
            throw new IllegalStateException("Call initialize() before getInstance()");
        }

        return sInstance;
    }

    private final Map<Target, Tracker> mTrackers = new HashMap<>();
    private final Context mContext;

    /**
     * Don't instantiate directly - use {@link #getInstance()} instead.
     */
    private MobilePayAnalyticsConf(Context context) {
        mContext = context.getApplicationContext();
    }

    public synchronized Tracker get(Target target) {
        if (!mTrackers.containsKey(target)) {
            Tracker mTracker;
            switch (target) {
                case APP:
                    GoogleAnalytics analytics = GoogleAnalytics.getInstance(mContext);
                    // To enable debug logging use: adb shell setprop log.tag.GAv4 DEBUG
                    mTracker = analytics.newTracker(R.xml.app_tracker);
                    break;
                default:
                    throw new IllegalArgumentException("Unhandled analytics target " + target);
            }
            mTrackers.put(target, mTracker);
        }

        return mTrackers.get(target);
    }
}
